name: "axiom_realtime"
version: "1.0.0"
config-version: 2
profile: "axiom"

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  axiom_realtime:
    staging:
      +materialized: view
    marts:
      +materialized: table
